---
#-------------------------------
# General Site Settings

title: 
logo:
author: 
description: this is meta description
email: jakeheinereng@gmail.com
phone: +1 (530) 227-5002
address: 697 E 3550 N, Ogden, UT 84414
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  # - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m Jake.


# About Section
blurb: Welcome to the World of Innovation and Creativity! 


blurb-btn-link: "/about"
blurb-btn-name: know more

#-------------------------------
# Experience Section

experience-title: Professional Experience
experience:
  - {
      name: Neuroscience Research Assistant,
      icon: "flask.png",
      date: "Jan 2016 - Jul 2018",
      organization: "Auburn University",
    }
  - {
      name: Process Engineer Intern,
      icon: "greenmachine.png",
      date: "Aug 2017 - Dec 2017",
      organization: "The Mosaic Company",
    }
  - {
      name: Process Design Engineer,
      icon: "molecularfamily.png",
      date: "May 2020 - Jul 2022",
      organization: "Dennis Group",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: B.S. Chemical Engineering,
      date: "2020",
      organization: "Auburn University",
    }


# Portfolio Page
portfolio-label:
  - { title: "Construction Management", type: "cm" }
  - { title: "Process Design", type: "design" }
  - { title: "Emerging Technologies", type: "newtech" }


skills-title: Skills
skills:
- name: Engineering Services QA/QC
  value: 90
  color: '#417B5A'
  description: "Experienced with Engineering Services QA/QC, ensuring high-quality standards."

- name: Industrial Design
  value: 70
  color: '#63ADF2'
  description: "Skilled in Industrial Design, creating functional and aesthetic products."

- name: Programmatic Engineering
  value: 90
  color: '#B185A7'
  description: "Expert in Programmatic Engineering, applying automation and programming techniques to engineering tasks."

- name: Client Relationships
  value: 80
  color: '#D1FFD7'
  description: "Strong in building and maintaining positive Client Relationships."

- name: Applied Machine Learning
  value: 70
  color: '#4A8EC8'
  description: "Proficient in Applied Machine Learning, implementing ML algorithms to solve real-world problems."

- name: Construction Management
  value: 80
  color: '#FF7F50'
  description: "Experienced in Construction Management, overseeing projects from start to finish."

- name: AutoCAD
  value: 70
  color: '#FFDAB9'
  description: "Skilled in AutoCAD, creating detailed 2D and 3D designs."

- name: Microsoft 365
  value: 90
  color: '#FFD700'
  description: "Proficient in Microsoft 365, utilizing its suite of productivity tools."

- name: Fusion360
  value: 50
  color: '#417B5A'
  description: "Skilled in Fusion360, creating 3D models and designs."

- name: Lean Six Sigma
  value: 80
  color: '#B185A7'
  description: "Knowledgeable in Lean Six Sigma, improving processes and reducing waste."

- name: Plant3D
  value: 50
  color: '#008080'
  description: "Proficient in Plant3D, designing and modeling plant facilities."

- name: Process Simulation
  value: 90
  color: '#40E0D0'
  description: "Experienced in Process Simulation, optimizing processes and predicting performance."

- name: As-Built & Future P&IDs
  value: 80
  color: '#FFD700'
  description: "Skilled in creating As-Built & Future P&IDs, documenting process systems."

- name: Functional Descriptions
  value: 90
  color: '#8E4585'
  description: "Experienced in writing Functional Descriptions, detailing system requirements and functions."

- name: Scope of Work Documentation
  value: 80
  color: '#FF7F50'
  description: "Skilled in preparing Scope of Work Documentation, defining project objectives and deliverables."

- name: Continuous Improvement
  value: 100
  color: '#40E0D0'
  description: "Dedicated to Continuous Improvement, constantly seeking ways to enhance performance and efficiency."


contact-title: Contact Info
contact-email: jakeheinereng@gmail.com
